Repository nuclearpasta/react-native-drax, pull requests merged in 2020-06, with the labels that each got.

#33 fix out-of-list drag bug; closes #27
  src/DraxList.tsx
Labels: DraxList, animation, bug

#34 upgrade devDependency to react-native 0.62; closes #30
  package.json
  yarn.lock
Labels: dependencies, security

#26 Add callback for when a dragged item changes indexes in the DraxList
  src/DraxList.tsx
  src/types.ts
Labels: DraxList, enhancement

#29 Speed up dragging animation to be at least 60fps
  src/DraxList.tsx
  src/DraxView.tsx
  src/hooks/useDraxRegistry.ts
Labels: animation, enhancement

#42 Fixes for #25 and #22
  src/DraxList.tsx
  src/DraxProvider.tsx
  src/types.ts
Labels: DraxList, bug, enhancement

#31 add snapbackAnimator prop to DraxView; potentially closes #28
  CHANGELOG.md
  src/DraxList.tsx
  src/DraxView.tsx
  src/hooks/useDraxRegistry.ts
  src/types.ts
Labels: animation, enhancement

#48 syntax highlighting on readme.md
  README.md
Labels: documentation
